blank_issues_enabled : true
contact_links:
  - name: Discord
    url: https://discord.gg/tTWcqrBB3t
    about: Discord support server
  - name: Forum
    url: https://forum.kerbalspaceprogram.com/topic/223692-1125-tweakscalerescaled-scale-your-parts-in-the-editor/
    about: KSP forum support thread
