blank_issues_enabled : true
contact_links:
  - name: Discord
    url: https://discord.gg/tTWcqrBB3t
    about: Discord support server
  - name: Forum
    url: https://forum.kerbalspaceprogram.com/topic/222953-1125-wip-tweakscale-rescaled/
    about: KSP forum support thread
